# AI GENERATED CODE
# DO NOT EDIT THIS FILE
import os
import json
from datetime import datetime, date
from decimal import Decimal
from pathlib import Path

import oracledb
from pymongo import MongoClient, ASCENDING, DESCENDING, GEOSPHERE


BASE_DIR = Path(__file__).resolve().parent


def load_local_env():
    env_file = BASE_DIR / ".env"
    if not env_file.exists():
        return

    for raw_line in env_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, _, value = line.partition("=")
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key.strip(), value)


load_local_env()

ORACLE_USER = os.getenv("ORACLE_USER", "ADMIN")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD")
ORACLE_WALLET_PATH = os.getenv("ORACLE_WALLET_PATH", "./Wallet_TC3004B")
ORACLE_DSN = os.getenv("ORACLE_DSN", "tc3004b_high")
ORACLE_WALLET_PASSWORD = os.getenv("ORACLE_WALLET_PASSWORD")

MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
MONGO_DB_NAME = os.getenv("MONGO_DB_NAME", "moviestream")


def resolve_wallet_dir():
    wallet_dir = Path(ORACLE_WALLET_PATH)
    if not wallet_dir.is_absolute():
        wallet_dir = (BASE_DIR / wallet_dir).resolve()

    if not wallet_dir.is_dir():
        raise FileNotFoundError(f"No se encontró el wallet en: {wallet_dir}")

    return wallet_dir


def connect_oracle():
    if not ORACLE_PASSWORD:
        raise ValueError("ORACLE_PASSWORD no está definida en el entorno o en .env")

    wallet_dir = resolve_wallet_dir()
    connect_kwargs = {
        "user": ORACLE_USER,
        "password": ORACLE_PASSWORD,
        "dsn": ORACLE_DSN,
        "config_dir": str(wallet_dir),
        "wallet_location": str(wallet_dir),
    }

    if ORACLE_WALLET_PASSWORD:
        connect_kwargs["wallet_password"] = ORACLE_WALLET_PASSWORD

    return oracledb.connect(**connect_kwargs)


def to_json_value(value):
    if value is None:
        return None

    if isinstance(value, Decimal):
        if value == value.to_integral_value():
            return int(value)
        return float(value)

    if isinstance(value, datetime):
        return value

    if isinstance(value, date):
        return datetime(value.year, value.month, value.day)

    if isinstance(value, bytes):
        return value.decode("utf-8")

    return value


def parse_json(value):
    if value is None:
        return None

    if isinstance(value, (dict, list)):
        return value

    if isinstance(value, bytes):
        value = value.decode("utf-8")

    if isinstance(value, str):
        value = value.strip()
        if value == "":
            return None
        try:
            return json.loads(value)
        except json.JSONDecodeError:
            return value

    return value


def row_to_dict(cursor, row):
    columns = [col[0].lower() for col in cursor.description]
    return {
        columns[i]: to_json_value(row[i])
        for i in range(len(columns))
    }


def fetch_all(conn, query, params=None):
    with conn.cursor() as cursor:
        cursor.execute(query, params or {})
        return [row_to_dict(cursor, row) for row in cursor]


def fetch_one_map(conn, query, key_field):
    rows = fetch_all(conn, query)
    return {
        row[key_field]: row
        for row in rows
        if row.get(key_field) is not None
    }


def bool_from_number(value):
    if value is None:
        return None
    return bool(value)


def bool_from_yn(value):
    if value is None:
        return None

    value = str(value).strip().upper()

    if value in ("Y", "YES", "TRUE", "1", "S", "SI", "S�"):
        return True

    if value in ("N", "NO", "FALSE", "0"):
        return False

    return value


def build_movies(conn):
    genre_by_id = fetch_one_map(
        conn,
        """
        SELECT
            genre_id,
            name
        FROM genre
        """,
        "genre_id",
    )

    movies = fetch_all(
        conn,
        """
        SELECT
            sku,
            cast,
            crew,
            year,
            genre,
            gross,
            title,
            views,
            awards,
            budget,
            studio,
            runtime,
            summary,
            movie_id,
            image_url,
            list_price,
            nominations,
            main_subject,
            opening_date,
            wiki_article,
            created_at
        FROM movie
        """,
    )

    docs = []

    for movie in movies:
        raw_genre = parse_json(movie.get("genre"))

        genres = []

        if isinstance(raw_genre, list):
            for item in raw_genre:
                if isinstance(item, dict):
                    genre_id = item.get("genre_id") or item.get("genreId") or item.get("id")
                    genre_name = item.get("name")
                    genres.append({
                        "genreId": genre_id,
                        "name": genre_name,
                    })
                else:
                    genres.append({
                        "genreId": None,
                        "name": item,
                    })

        elif isinstance(raw_genre, dict):
            genre_id = raw_genre.get("genre_id") or raw_genre.get("genreId") or raw_genre.get("id")
            genre_name = raw_genre.get("name")
            genres.append({
                "genreId": genre_id,
                "name": genre_name,
            })

        elif raw_genre is not None:
            genres.append({
                "genreId": None,
                "name": raw_genre,
            })

        doc = {
            "_id": movie.get("movie_id"),
            "sku": movie.get("sku"),
            "title": movie.get("title"),
            "year": movie.get("year"),
            "runtime": movie.get("runtime"),
            "summary": movie.get("summary"),
            "mainSubject": movie.get("main_subject"),
            "openingDate": movie.get("opening_date"),
            "imageUrl": movie.get("image_url"),
            "wikiArticle": movie.get("wiki_article"),
            "listPrice": movie.get("list_price"),
            "views": movie.get("views"),
            "budget": movie.get("budget"),
            "gross": movie.get("gross"),
            "genres": genres,
            "cast": parse_json(movie.get("cast")),
            "crew": parse_json(movie.get("crew")),
            "studio": parse_json(movie.get("studio")),
            "awards": parse_json(movie.get("awards")),
            "nominations": parse_json(movie.get("nominations")),
            "createdAt": movie.get("created_at"),
        }

        docs.append(doc)

    return docs


def build_customers(conn):
    segments = fetch_one_map(
        conn,
        """
        SELECT
            segment_id,
            name,
            short_name
        FROM customer_segment
        """,
        "segment_id",
    )

    surveys = fetch_one_map(
        conn,
        """
        SELECT
            cust_id,
            completed_survey,
            rating,
            would_recommend,
            interested_in_premium_tier,
            interested_in_exclusive_offerings,
            mobile_device,
            television
        FROM customer_survey
        """,
        "cust_id",
    )

    feedback_rows = fetch_all(
        conn,
        """
        SELECT
            day,
            userid,
            city,
            state_province,
            country,
            continent,
            customer_comments,
            email,
            cust_id
        FROM customer_feedback
        """,
    )

    feedback_by_customer = {}

    for feedback in feedback_rows:
        cust_id = feedback.get("cust_id")
        if cust_id is None:
            continue

        feedback_by_customer.setdefault(cust_id, []).append({
            "day": feedback.get("day"),
            "userId": feedback.get("userid"),
            "city": feedback.get("city"),
            "stateProvince": feedback.get("state_province"),
            "country": feedback.get("country"),
            "continent": feedback.get("continent"),
            "comments": feedback.get("customer_comments"),
            "email": feedback.get("email"),
        })

    customers = fetch_all(
        conn,
        """
        SELECT
            cust_id,
            last_name,
            first_name,
            email,
            street_address,
            postal_code,
            city,
            state_province,
            country,
            country_code,
            continent,
            yrs_customer,
            promotion_response,
            loc_lat,
            loc_long,
            age,
            commute_distance,
            credit_balance,
            education,
            full_time,
            gender,
            household_size,
            income,
            income_level,
            insuff_funds_incidents,
            job_type,
            late_mort_rent_pmts,
            marital_status,
            mortgage_amt,
            num_cars,
            num_mortgages,
            pet,
            rent_own,
            segment_id,
            work_experience,
            yrs_current_employer,
            yrs_residence
        FROM customer
        """,
    )

    docs = []

    for customer in customers:
        cust_id = customer.get("cust_id")
        segment = segments.get(customer.get("segment_id"))
        survey = surveys.get(cust_id)

        coordinates = None
        if customer.get("loc_long") is not None and customer.get("loc_lat") is not None:
            coordinates = [customer.get("loc_long"), customer.get("loc_lat")]

        doc = {
            "_id": cust_id,
            "firstName": customer.get("first_name"),
            "lastName": customer.get("last_name"),
            "email": customer.get("email"),
            "address": {
                "street": customer.get("street_address"),
                "postalCode": customer.get("postal_code"),
                "city": customer.get("city"),
                "stateProvince": customer.get("state_province"),
                "country": customer.get("country"),
                "countryCode": customer.get("country_code"),
                "continent": customer.get("continent"),
            },
            "location": {
                "type": "Point",
                "coordinates": coordinates,
            } if coordinates else None,
            "customerInfo": {
                "yearsCustomer": customer.get("yrs_customer"),
                "promotionResponse": customer.get("promotion_response"),
            },
            "demographics": {
                "age": customer.get("age"),
                "commuteDistance": customer.get("commute_distance"),
                "creditBalance": customer.get("credit_balance"),
                "education": customer.get("education"),
                "fullTime": customer.get("full_time"),
                "gender": customer.get("gender"),
                "householdSize": customer.get("household_size"),
                "income": customer.get("income"),
                "incomeLevel": customer.get("income_level"),
                "insufficientFundsIncidents": customer.get("insuff_funds_incidents"),
                "jobType": customer.get("job_type"),
                "lateMortgageRentPayments": customer.get("late_mort_rent_pmts"),
                "maritalStatus": customer.get("marital_status"),
                "mortgageAmount": customer.get("mortgage_amt"),
                "numCars": customer.get("num_cars"),
                "numMortgages": customer.get("num_mortgages"),
                "pet": customer.get("pet"),
                "rentOwn": customer.get("rent_own"),
                "workExperience": customer.get("work_experience"),
                "yearsCurrentEmployer": customer.get("yrs_current_employer"),
                "yearsResidence": customer.get("yrs_residence"),
            },
            "segment": {
                "segmentId": segment.get("segment_id"),
                "name": segment.get("name"),
                "shortName": segment.get("short_name"),
            } if segment else None,
            "survey": {
                "completedSurvey": bool_from_yn(survey.get("completed_survey")),
                "rating": survey.get("rating"),
                "wouldRecommend": bool_from_yn(survey.get("would_recommend")),
                "interestedInPremiumTier": bool_from_yn(survey.get("interested_in_premium_tier")),
                "interestedInExclusiveOfferings": bool_from_yn(survey.get("interested_in_exclusive_offerings")),
                "mobileDevice": bool_from_yn(survey.get("mobile_device")),
                "television": bool_from_yn(survey.get("television")),
            } if survey else None,
            "feedback": feedback_by_customer.get(cust_id, []),
        }

        docs.append(doc)

    return docs


def build_subscription_plans(conn):
    rows = fetch_all(
        conn,
        """
        SELECT
            plan_id,
            name,
            retention_days,
            allows_alerts,
            price
        FROM subscription_plans
        """,
    )

    return [
        {
            "_id": row.get("plan_id"),
            "name": row.get("name"),
            "retentionDays": row.get("retention_days"),
            "allowsAlerts": bool_from_number(row.get("allows_alerts")),
            "price": row.get("price"),
        }
        for row in rows
    ]


def build_devices(conn):
    rows = fetch_all(
        conn,
        """
        SELECT
            device_id,
            mac_address,
            model,
            device_type
        FROM devices
        """,
    )

    return [
        {
            "_id": row.get("device_id"),
            "macAddress": row.get("mac_address"),
            "model": row.get("model"),
            "deviceType": row.get("device_type"),
        }
        for row in rows
    ]


def build_users(conn):
    plans = {
        plan["_id"]: plan
        for plan in build_subscription_plans(conn)
    }

    devices = {
        device["_id"]: device
        for device in build_devices(conn)
    }

    user_device_rows = fetch_all(
        conn,
        """
        SELECT
            user_device_id,
            user_id,
            device_id,
            assigned_at,
            unassigned_at
        FROM user_devices
        """,
    )

    user_devices_by_user = {}

    for row in user_device_rows:
        user_id = row.get("user_id")
        device_id = row.get("device_id")
        device = devices.get(device_id)

        user_devices_by_user.setdefault(user_id, []).append({
            "userDeviceId": row.get("user_device_id"),
            "deviceId": device_id,
            "assignedAt": row.get("assigned_at"),
            "unassignedAt": row.get("unassigned_at"),
            "deviceSnapshot": {
                "macAddress": device.get("macAddress"),
                "model": device.get("model"),
                "deviceType": device.get("deviceType"),
            } if device else None,
        })

    users = fetch_all(
        conn,
        """
        SELECT
            user_id,
            plan_id,
            name,
            email,
            created_at
        FROM users
        """,
    )

    docs = []

    for user in users:
        plan = plans.get(user.get("plan_id"))

        docs.append({
            "_id": user.get("user_id"),
            "name": user.get("name"),
            "email": user.get("email"),
            "createdAt": user.get("created_at"),
            "planId": user.get("plan_id"),
            "planSnapshot": {
                "name": plan.get("name"),
                "retentionDays": plan.get("retentionDays"),
                "allowsAlerts": plan.get("allowsAlerts"),
                "price": plan.get("price"),
            } if plan else None,
            "devices": user_devices_by_user.get(user.get("user_id"), []),
        })

    return docs


def build_activities(conn):
    movies = fetch_one_map(
        conn,
        """
        SELECT
            movie_id,
            title,
            year
        FROM movie
        """,
        "movie_id",
    )

    genres = fetch_one_map(
        conn,
        """
        SELECT
            genre_id,
            name
        FROM genre
        """,
        "genre_id",
    )

    rows = fetch_all(
        conn,
        """
        SELECT
            os,
            app,
            device,
            cust_id,
            activity,
            genre_id,
            movie_id,
            activity_time
        FROM activity
        """,
    )

    docs = []

    for index, row in enumerate(rows, start=1):
        movie = movies.get(row.get("movie_id"))
        genre = genres.get(row.get("genre_id"))

        docs.append({
            "_id": f"activity_{index}",
            "customerId": row.get("cust_id"),
            "movieId": row.get("movie_id"),
            "genreId": row.get("genre_id"),
            "activity": row.get("activity"),
            "activityTime": row.get("activity_time"),
            "device": {
                "name": row.get("device"),
                "type": None,
            },
            "app": row.get("app"),
            "os": row.get("os"),
            "movieSnapshot": {
                "title": movie.get("title"),
                "year": movie.get("year"),
            } if movie else None,
            "genreSnapshot": {
                "genreId": genre.get("genre_id"),
                "name": genre.get("name"),
            } if genre else None,
        })

    return docs


def build_user_sessions(conn):
    rows = fetch_all(
        conn,
        """
        SELECT
            session_id,
            cust_id,
            start_time,
            end_time,
            elapsed_time
        FROM user_sessions
        """,
    )

    return [
        {
            "_id": row.get("session_id"),
            "customerId": row.get("cust_id"),
            "startTime": row.get("start_time"),
            "endTime": row.get("end_time"),
            "elapsedTime": row.get("elapsed_time"),
        }
        for row in rows
    ]


def replace_collection(db, collection_name, docs):
    collection = db[collection_name]
    collection.drop()

    if docs:
        collection.insert_many(docs, ordered=False)

    print(f"{collection_name}: {len(docs)} documentos migrados")


def create_indexes(db):
    db.movies.create_index([("title", ASCENDING)])
    db.movies.create_index([("genres.name", ASCENDING)])
    db.movies.create_index([("year", ASCENDING)])
    db.movies.create_index([("views", DESCENDING)])

    db.customers.create_index([("email", ASCENDING)])
    db.customers.create_index([("segment.segmentId", ASCENDING)])
    db.customers.create_index([("address.country", ASCENDING)])
    db.customers.create_index([("location", GEOSPHERE)])

    db.activities.create_index([("customerId", ASCENDING), ("activityTime", DESCENDING)])
    db.activities.create_index([("movieId", ASCENDING), ("activityTime", DESCENDING)])
    db.activities.create_index([("genreSnapshot.name", ASCENDING), ("activityTime", DESCENDING)])

    db.users.create_index([("email", ASCENDING)])
    db.users.create_index([("planId", ASCENDING)])
    db.users.create_index([("devices.deviceId", ASCENDING)])

    db.devices.create_index([("macAddress", ASCENDING)])

    db.subscription_plans.create_index([("name", ASCENDING)])

    db.user_sessions.create_index([("customerId", ASCENDING), ("startTime", DESCENDING)])

    print("�ndices creados")


def main():
    oracle_conn = connect_oracle()

    mongo_client = MongoClient(MONGO_URI)
    mongo_db = mongo_client[MONGO_DB_NAME]

    try:
        print("Construyendo documentos desde Oracle...")

        movies = build_movies(oracle_conn)
        customers = build_customers(oracle_conn)
        subscription_plans = build_subscription_plans(oracle_conn)
        devices = build_devices(oracle_conn)
        users = build_users(oracle_conn)
        activities = build_activities(oracle_conn)
        user_sessions = build_user_sessions(oracle_conn)

        print("Insertando documentos en MongoDB...")

        replace_collection(mongo_db, "movies", movies)
        replace_collection(mongo_db, "customers", customers)
        replace_collection(mongo_db, "subscription_plans", subscription_plans)
        replace_collection(mongo_db, "devices", devices)
        replace_collection(mongo_db, "users", users)
        replace_collection(mongo_db, "activities", activities)
        replace_collection(mongo_db, "user_sessions", user_sessions)

        create_indexes(mongo_db)

        print("Migraci�n completada correctamente")

    finally:
        oracle_conn.close()
        mongo_client.close()


if __name__ == "__main__":
    main()